#page title
page_title                                : Stats - Health, Fitness Widget            # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1577041780                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Stats - Health, Fitness Widget            # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : A beautiful Apple Health widget for iOS.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : James Shaw
your_link                                 : https://www.shaw-james.com
your_city                                 : York, England
email_address                             :
facebook_username                         :
instagram_username                        : jsh8w
twitter_username                          : jsh8w
github_username                           : jsh8w
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Apple Health Widget
    description                           : View Apple Health data right on your iPhone home screen.
    fontawesome_icon_name                 : heart

  - title                                 : 14 Health Metrics
    description                           : Choose between 14 different Health metrics to visualise.
    fontawesome_icon_name                 : weight

  - title                                 : Graphs and Charts
    description                           : Visualise Health data with beautiful charts and graphs.
    fontawesome_icon_name                 : chart-bar

  - title                                 : Time Periods
    description                           : View data for different time periods such as past 7 or 30 days.
    fontawesome_icon_name                 : clock

  - title                                 : Beautiful iOS 14 Widget
    description                           : Designed for specifically for iOS 14 Devices and the Apple WidgetKit SDK.
    fontawesome_icon_name                 : mobile

  - title                                 : Customisation
    description                           : Customise the style of widgets by selecting between sizes and themes.
    fontawesome_icon_name                 : palette



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 0.7

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#FF0000"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#e12727"
feature_icons_background_color            : "#282828"

social_icons_foreground_color             : "#e12727"
social_icons_background_color             : "#282828"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
